spring.application.name=smart-campus

spring.datasource.url=jdbc:postgresql://ep-round-frost-amsrrabu.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_16nCwrPsDENG
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Security - temporarily disable strong enforcement for easier feature testing
spring.security.user.name=admin
spring.security.user.password=admin
